### ISSUE TITLE
Initial TODO list

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/mason.rpkg#1]
- [x] Suggest testthat, if used.
- [x] Create better .R file
- [x] Create manual file
- [x] Travis, Appveyor shields only if requested
- [ ] Code coverage tools
- [x] Create git repo
- [x] Create repo on GitHub, if user has a token
- [x] Push first version, right after the package was created
- [x] Get gh_username automatically, if possible
- [x] LICENSE file, if needed

**Comment by gaborcsardi** [comment]
All done, except coverage tools, but that can be added later.
